// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMeBlock: typeof import('./src/components/home/AboutMeBlock.vue')['default']
    ContactMeBlock: typeof import('./src/components/home/ContactMeBlock.vue')['default']
    DecorativeAsterisks: typeof import('./src/components/reusable/decorative-asterisks.vue')['default']
    DecorativeBox: typeof import('./src/components/reusable/decorative-box.vue')['default']
    FloatingBackButton: typeof import('./src/components/home/FloatingBackButton.vue')['default']
    MyProjectsBlock: typeof import('./src/components/home/MyProjectsBlock.vue')['default']
    MyWorkBlock: typeof import('./src/components/home/MyWorkBlock.vue')['default']
    PixelButton: typeof import('./src/components/pixel/PixelButton.vue')['default']
    PixelPopup: typeof import('./src/components/pixel/PixelPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SummaryBlock: typeof import('./src/components/home/SummaryBlock.vue')['default']
    TitleBlock: typeof import('./src/components/home/TitleBlock.vue')['default']
  }
}
